import { Component } from '@angular/core';
import { HelloComponent } from './hello/hello.component';
import { Title } from '@angular/platform-browser';
import { RecordsService } from './records.service';

function log(className) {
  console.log("The className is ", className);
  return (...args) => {
    console.log("Arguments passed to this class's constructor are ", args);
    return new className(...args);
  };
}

// @log
// class myExampleClass {
//   constructor(arg1,arg2) {
//     console.log("Constructor fired!", arg1, arg2);
//   }
// }

// const myClass = new myExampleClass(5,10);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})

export class AppComponent {
  title = 'intro2angular';
  name = 'Name';
  text2 = 'text2';
  
  constructor(private myFirstService : RecordsService) {
    console.log("This statement was generated by the constructor", this.aSimpleMethod(3));
  };

  ngOnInit() {
  };

  updateValue(e) {
    this.name = e.target.value;
  };

  aSimpleMethod(a) {
    return a*a;
  }
}
